---
# tasks file for apache
- name: stop iptables
  service: name=iptables state=stopped
  
- name: install packages
  yum: name={{ item }} state=present
  with_items: packages
  tags: package

- name: copy httpd.conf
  template: src=httpd.conf.j2 dest=/etc/httpd/httpd.conf
  notify: restart apache

- name: copy index.html
  template: src=index.html.j2 dest=/var/www/html/index.html

- name: start and enable apache service
  service: name=httpd state=started enabled=yes
  tags: service