---
# tasks file for infra
- name: create vpc
  ec2_vpc:
    state: present
    cidr_block: 172.22.0.0/16
    resource_tags: { "Name":"Training" }
    subnets:
      - cidr: 172.22.1.0/24
        resource_tags: { "Name":"Training" }
    internet_gateway: True
    route_tables:
      - subnets:
          - 172.22.1.0/24
        routes:
          - dest: 0.0.0.0/0
            gw: igw
    region: us-east-1
    wait: yes
  register: vpc

- name: create admin access 
  ec2_group:
    name: admin_access
    description: SSH access for admins and tower
    region: us-east-1
    vpc_id: "{{ vpc.vpc_id }}"
    rules:
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 0.0.0.0/0
  register: admin_access

- name: create app security group
  ec2_group:
    name: web-test
    description: web security group
    region: us-east-1
    rules:
      - proto: tcp
        from_port: 80
        to_port: 80
        cidr_ip: 0.0.0.0/0
    vpc_id: "{{ vpc.vpc_id }}"
  tags: security_groups
  register: app_security_group


- name: launch instance
  ec2:
    key_name: jmartin
    instance_type: m3.medium
    image: ami-8997afe0
    wait: yes
    region: us-east-1
    group_id:
    - "{{ app_security_group.group_id }}"
    - "{{ admin_access.group_id }}"
    instance_tags:
      Name: shellshock
    exact_count: 1
    vpc_subnet_id: "{{ vpc.subnets[0].id }}"
    count_tag:
      Name: shellshock
    assign_public_ip: yes
  register: instances

- name: add host to inventory group
  add_host:
    hostname: "{{ item.public_ip }}" 
    groupname: launched
  with_items: instances.tagged_instances

- name: wait for ssh to spin up
  wait_for: 
    host: "{{ item.public_ip }}" 
    port: 22 
    timeout: 320 
    state: started
    search_regex: OpenSSH
  with_items: instances.tagged_instances

- name: wait a bit longer
  pause:
    seconds: 10
